### ISSUE TITLE
History mode faillure

### ISSUE THREAD

**Issue by Paluche85** [ronki2304/WhiteCow#1]
after some hours, history mode fails and is not able to restart. 
The last row in histroy.csv sems to be good. 

workaround find : 

- stop service
- rm history.csv 
- rm lock file 
- restart service

log during last occurrency : 
### 
Dec 03 19:17:24 RaspberryMick mono-service[17725]: 03/12/2017 19:17:24;3.3738;;3
Dec 03 19:17:36 RaspberryMick mono-service[17725]: 03/12/2017 19:17:36;3.3738;;3
Dec 03 19:17:44 RaspberryMick mono-service[17725]: 03/12/2017 19:17:44;3.3738;;3
Dec 03 19:17:54 RaspberryMick mono-service[17725]: Unhandled Exception:
Dec 03 19:17:54 RaspberryMick mono-service[17725]: System.Net.WebException: The
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Net.WebClient.Dow
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Net.WebClient.Dow
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Net.WebClient.Dow
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at (wrapper remoting-invoke
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at WhiteCow.Broker.BitFinex
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at WhiteCow.Broker.Broker.g
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at WhiteCow.RuntimeMode.His
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Threading.Timer+S
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Threading.QueueUs
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Threading.ThreadP
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Threading._Thread
Dec 03 19:17:54 RaspberryMick mono-service[17725]: [ERROR] FATAL UNHANDLED EXCEP
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Net.WebClient.Dow
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Net.WebClient.Dow
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Net.WebClient.Dow
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at (wrapper remoting-invoke
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at WhiteCow.Broker.BitFinex
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at WhiteCow.Broker.Broker.g
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at WhiteCow.RuntimeMode.His
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Threading.Timer+S
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Threading.QueueUs
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Threading.ThreadP
Dec 03 19:17:54 RaspberryMick mono-service[17725]:   at System.Threading._Thread
Dec 03 19:17:54 RaspberryMick systemd[1]: WhiteCow.service: Main process exited,
Dec 03 19:17:54 RaspberryMick systemd[1]: WhiteCow.service: Unit entered failed
Dec 03 19:17:54 RaspberryMick systemd[1]: WhiteCow.service: Failed with result '
Dec 03 19:18:04 RaspberryMick systemd[1]: WhiteCow.service: Service hold-off tim
Dec 03 19:18:04 RaspberryMick systemd[1]: Stopped Test service.
Dec 03 19:18:04 RaspberryMick systemd[1]: Started Test service.
Dec 03 19:18:04 RaspberryMick mono[18097]: /home/mickael/WhiteCow/WhiteCow/bin/R
Dec 03 19:18:04 RaspberryMick systemd[1]: WhiteCow.service: Main process exited,
Dec 03 19:18:04 RaspberryMick systemd[1]: WhiteCow.service: Unit entered failed
Dec 03 19:18:04 RaspberryMick systemd[1]: WhiteCow.service: Failed with result '
Dec 03 19:18:14 RaspberryMick systemd[1]: WhiteCow.service: Service hold-off tim
Dec 03 19:18:14 RaspberryMick systemd[1]: Stopped Test service.
Dec 03 19:18:14 RaspberryMick systemd[1]: Started Test service.
Dec 03 19:18:14 RaspberryMick mono[18102]: /home/mickael/WhiteCow/WhiteCow/bin/R
Dec 03 19:18:14 RaspberryMick systemd[1]: WhiteCow.service: Main process exited,
Dec 03 19:18:14 RaspberryMick systemd[1]: WhiteCow.service: Unit entered failed
Dec 03 19:18:14 RaspberryMick systemd[1]: WhiteCow.service: Failed with result '
Dec 03 19:18:24 RaspberryMick systemd[1]: WhiteCow.service: Service hold-off tim
Dec 03 19:18:24 RaspberryMick systemd[1]: Stopped Test service.
Dec 03 19:18:24 RaspberryMick systemd[1]: Started Test service.
Dec 03 19:18:25 RaspberryMick mono[18107]: /home/mickael/WhiteCow/WhiteCow/bin/R

Dec 03 22:02:45 RaspberryMick mono[23228]: /home/mickael/WhiteCow/WhiteCow/bin/Release/WhiteCow.exe: Lock file alread
Dec 03 22:02:45 RaspberryMick systemd[1]: WhiteCow.service: Main process exited, code=exited, status=1/FAILURE
Dec 03 22:02:45 RaspberryMick systemd[1]: WhiteCow.service: Unit entered failed state.
Dec 03 22:02:45 RaspberryMick systemd[1]: WhiteCow.service: Failed with result 'exit-code'.
Dec 03 22:02:55 RaspberryMick systemd[1]: WhiteCow.service: Service hold-off time over, scheduling restart.
Dec 03 22:02:55 RaspberryMick systemd[1]: Stopped Test service.
Dec 03 22:02:55 RaspberryMick systemd[1]: Started Test service.

**Comment by ronki2304** [comment]
Find the issue,

HTTP error are unhandled 

fixed it
